import { User, Thread, Message, ExtractedEntity, ActivityItem } from './types'

export const mockUsers: User[] = [
  { id: 'user1', name: 'Alex Chen', email: 'alex@example.com', voiceEnabled: true },
  { id: 'user2', name: 'Sam Rivera', email: 'sam@example.com', voiceEnabled: true },
  { id: 'user3', name: 'Jordan Kim', email: 'jordan@example.com', voiceEnabled: false },
]

export const mockThreads: Thread[] = [
  {
    id: 'thread1',
    groupId: 'group1',
    participants: ['user1', 'user2'],
    title: 'Weekend Plans',
    lastActivity: '2024-01-15T10:30:00Z',
    unreadCount: 2,
    importanceScore: 0.85,
    mlSummary: 'Planning weekend trip to mountains, discussing dates and activities',
    unresolvedCount: 3,
  },
  {
    id: 'thread2',
    groupId: 'group1',
    participants: ['user1', 'user2', 'user3'],
    title: 'Project Decisions',
    lastActivity: '2024-01-15T09:15:00Z',
    unreadCount: 0,
    importanceScore: 0.92,
    mlSummary: 'Key decisions about architecture and timeline',
    unresolvedCount: 5,
  },
  {
    id: 'thread3',
    groupId: 'group1',
    participants: ['user1', 'user3'],
    title: 'Family Dinner',
    lastActivity: '2024-01-14T18:00:00Z',
    unreadCount: 1,
    importanceScore: 0.45,
    mlSummary: 'Coordinating dinner plans for next week',
    unresolvedCount: 1,
  },
]

export const mockMessages: Record<string, Message[]> = {
  thread1: [
    {
      id: 'msg1',
      threadId: 'thread1',
      senderId: 'user1',
      type: 'text',
      content: 'Hey! Want to go hiking this weekend? I was thinking Saturday morning.',
      timestamp: '2024-01-15T09:00:00Z',
      entities: ['entity1'],
    },
    {
      id: 'msg2',
      threadId: 'thread1',
      senderId: 'user2',
      type: 'text',
      content: 'Sounds great! Can we make it Sunday instead? I have something Saturday.',
      timestamp: '2024-01-15T09:15:00Z',
    },
    {
      id: 'msg3',
      threadId: 'thread1',
      senderId: 'user1',
      type: 'text',
      content: 'Sunday works! Let\'s meet at the trailhead at 8am. I\'ll bring snacks.',
      timestamp: '2024-01-15T09:30:00Z',
      entities: ['entity1', 'entity2'],
    },
    {
      id: 'msg4',
      threadId: 'thread1',
      senderId: 'user2',
      type: 'voice',
      content: 'Perfect, see you then!',
      audioUrl: '/audio/msg4.mp3',
      waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.5, 0.7],
      timestamp: '2024-01-15T10:30:00Z',
    },
  ],
  thread2: [
    {
      id: 'msg5',
      threadId: 'thread2',
      senderId: 'user1',
      type: 'text',
      content: 'I think we should use React for the frontend. It\'s what the team knows best.',
      timestamp: '2024-01-15T08:00:00Z',
      entities: ['entity3'],
    },
    {
      id: 'msg6',
      threadId: 'thread2',
      senderId: 'user2',
      type: 'text',
      content: 'Agreed. Let\'s finalize this decision and move forward.',
      timestamp: '2024-01-15T08:15:00Z',
      entities: ['entity3'],
    },
  ],
}

export const mockEntities: ExtractedEntity[] = [
  {
    id: 'entity1',
    type: 'plan',
    title: 'Weekend Hiking Trip',
    description: 'Hiking trip planned for Sunday',
    status: 'confirmed',
    ownerId: 'user1',
    threadId: 'thread1',
    messageId: 'msg1',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-01-15T09:30:00Z',
    lastTouchedBy: 'user1',
    metadata: {
      date: '2024-01-21',
      time: '8:00 AM',
      participants: ['user1', 'user2'],
      location: 'Trailhead',
      priority: 'medium',
    },
    importanceScore: 0.75,
    voiceSummaryUrl: '/audio/entity1-summary.mp3',
  },
  {
    id: 'entity2',
    type: 'promise',
    title: 'Bring snacks for hike',
    description: 'Alex will bring snacks',
    status: 'pending',
    ownerId: 'user1',
    threadId: 'thread1',
    messageId: 'msg3',
    createdAt: '2024-01-15T09:30:00Z',
    updatedAt: '2024-01-15T09:30:00Z',
    importanceScore: 0.45,
  },
  {
    id: 'entity3',
    type: 'decision',
    title: 'Use React for frontend',
    description: 'Team decision to use React',
    status: 'confirmed',
    ownerId: 'user1',
    threadId: 'thread2',
    messageId: 'msg5',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:15:00Z',
    lastTouchedBy: 'user2',
    importanceScore: 0.92,
  },
  {
    id: 'entity4',
    type: 'recommendation',
    title: 'Try the new Italian restaurant',
    description: 'Sam recommended trying the new place downtown',
    status: 'proposed',
    ownerId: 'user2',
    threadId: 'thread3',
    messageId: 'msg7',
    createdAt: '2024-01-14T18:00:00Z',
    updatedAt: '2024-01-14T18:00:00Z',
    importanceScore: 0.35,
  },
  {
    id: 'entity5',
    type: 'memory',
    title: 'Last family dinner',
    description: 'Remember when we all went to that place and had the amazing pasta?',
    status: 'resolved',
    ownerId: 'user3',
    threadId: 'thread3',
    messageId: 'msg8',
    createdAt: '2024-01-10T19:00:00Z',
    updatedAt: '2024-01-10T19:00:00Z',
    importanceScore: 0.60,
  },
]

export const mockActivities: ActivityItem[] = [
  {
    id: 'act1',
    type: 'decision_made',
    entityId: 'entity3',
    threadId: 'thread2',
    messageId: 'msg6',
    userId: 'user2',
    description: 'Confirmed decision: Use React for frontend',
    timestamp: '2024-01-15T08:15:00Z',
    importance: 0.92,
  },
  {
    id: 'act2',
    type: 'item_resolved',
    entityId: 'entity5',
    threadId: 'thread3',
    userId: 'user3',
    description: 'Resolved memory: Last family dinner',
    timestamp: '2024-01-10T19:00:00Z',
    importance: 0.60,
  },
  {
    id: 'act3',
    type: 'memory_resurfaced',
    entityId: 'entity5',
    threadId: 'thread3',
    userId: 'system',
    description: 'Resurfaced memory about family dinner',
    timestamp: '2024-01-14T17:30:00Z',
    importance: 0.60,
  },
]

